### ISSUE TITLE
Which file to run for running these scripts??

### ISSUE THREAD

**Issue by version0chiro** [guptaankit894/Heart-rate-and-SpO2#1]

**Comment by guptaankit894** [comment]
Thanks for the query.

"SpOO_heartrate.m"  is the main file which allows you to run all the scripts.

**Comment by version0chiro** [comment]
The heart rate estimation is not accurate, is the accuracy universal or is it working fine for you?

**Comment by guptaankit894** [comment]
I am sorry,I did not measure the accuracy. I checked 3-4 samples using this and it was running fine for them.

But for the sake of analysis,you can consider the performance metrics mentioned in the paper entitled "non-contact estimation of heart rate and oxygen saturation using ambient light".

As it is just the replica of this work.
